using System;
using Mexc.Net.Enums;

namespace Mexc.Net.Interfaces
{
    /// <summary>
    /// Order Info
    /// </summary>
    public interface IMexcV3GetOrderResponse
    {
        /// <summary>
        /// 错误提示消息
        /// </summary>
        string? ErrorMessage { get; set; }

        /// <summary>
        /// 错误编码
        /// </summary>
        long? ErrorCode { get; set; }

        /// <summary>
        /// 错误扩展信息
        /// </summary>
        string? Extend { get; set; }

        /// <summary>
        /// The symbol the order is for
        /// 交易代码
        /// </summary>
        string Symbol { get; set; }

        /// <summary>
        /// The order id generated by Mexc
        /// 订单编号
        /// </summary>
        string OrderId { get; set; }

        /// <summary>
        /// The order List Id by Mexc
        /// OCO订单ID，否则为 -1
        /// </summary>
        string OrderListId { get; set; }

        /// <summary>
        /// The clientOrderId id generated by Mexc
        /// 订单的用户自定义唯一单号
        /// </summary>
        string? ClientOrderId { get; set; }

        /// <summary>
        /// The price of the order
        /// 下单价格
        /// </summary>
        decimal Price { get; set; }

        /// <summary>
        /// The original quantity of the order, as specified in the order parameters by the user
        /// 下单数量
        /// </summary>
        decimal Quantity { get; set; }

        /// <summary>
        /// The currently executed quantity of the order
        /// 已成交数量
        /// </summary>
        decimal QuantityFilled { get; set; }

        /// <summary>
        /// The currently executed amount of quote asset. Amounts to Sum(quantity * price) of executed trades for this order
        /// 未成交数量
        /// </summary>
        decimal QuoteQuantityFilled { get; set; }

        /// <summary>
        /// The status of the order
        /// 订单状态
        /// </summary>
        OrderStatus? Status { get; set; }

        /// <summary>
        /// 订单的时效方式
        /// </summary>
        TimeInForce? TimeInForce { get; set; }

        /// <summary>
        /// The type of the order
        /// 订单类型
        /// </summary>
        SpotOrderType Type { get; set; }

        /// <summary>
        /// The side of the order
        /// 订单方向
        /// </summary>
        OrderSide Side { get; set; }

        /// <summary>
        /// stop price
        /// 止损价格
        /// </summary>
        string? StopPrice { get; set; }

        /// <summary>
        /// stop price
        /// 冰山数量
        /// </summary>
        string? IcebergQty { get; set; }

        /// <summary>
        /// Order created time
        /// 订单创建时间
        /// </summary>
        DateTime CreateTime { get; set; }

        /// <summary>
        /// Order update time
        /// 订单最后更新时间
        /// </summary>
        DateTime? UpdateTime { get; set; }

        /// <summary>
        /// is order book
        /// 是否在orderbook中
        /// </summary>
        bool IsWorking { get; set; }

        /// <summary>
        /// is order book
        /// 原始的交易金额
        /// </summary>
        decimal? QuoteQuantity { get; set; }
    }
}

