using Mexc.Net.Converters;
using Mexc.Net.Enums;
using Newtonsoft.Json;

namespace Mexc.Net.Objects.Models.Spot
{
    /// <summary>
    /// Order info
    /// </summary>
    public class MexcV3CancelOrderResponse
    {
        /// <summary>
        /// 错误提示消息
        /// </summary>
        [JsonProperty("msg")]
        public string? ErrorMessage { get; set; } = string.Empty;

        /// <summary>
        /// 错误编码
        /// </summary>
        [JsonProperty("code")]
        public long? ErrorCode { get; set; }

        /// <summary>
        /// 错误扩展信息
        /// </summary>
        [JsonProperty("_extend")]
        public string? Extend { get; set; }

        /// <summary>
        /// The symbol the order is for
        /// 交易代码
        /// </summary>
        [JsonProperty("symbol")]
        public string Symbol { get; set; } = string.Empty;

        /// <summary>
        /// The clientOrderId id generated by Mexc
        /// 原始订单的用户自定义唯一单号
        /// </summary>
        [JsonProperty("origClientOrderId")]
        public string? ClientOrderId { get; set; }

        /// <summary>
        /// The order id generated by Mexc
        /// 订单编号
        /// </summary>
        [JsonProperty("orderId")]
        public string OrderId { get; set; }

        private decimal _price;

        /// <summary>
        /// The price of the order
        /// 下单价格
        /// </summary>
        [JsonProperty("price")]
        public decimal Price
        {
            get
            {
                if (_price == 0 && Type == SpotOrderType.Market && QuantityFilled != 0)
                    return QuoteQuantityFilled / QuantityFilled;
                return _price;
            }
            set => _price = value;
        }

        /// <summary>
        /// The original quantity of the order, as specified in the order parameters by the user
        /// 下单数量
        /// </summary>
        [JsonProperty("origQty")]
        public decimal Quantity { get; set; }

        /// <summary>
        /// The type of the order
        /// 订单类型
        /// </summary>
        [JsonProperty("type"), JsonConverter(typeof(SpotOrderTypeConverter))]
        public SpotOrderType Type { get; set; }

        /// <summary>
        /// The side of the order
        /// 订单方向
        /// </summary>
        [JsonProperty("side"), JsonConverter(typeof(OrderSideConverter))]
        public OrderSide Side { get; set; }

        /// <summary>
        /// The currently executed quantity of the order
        /// 已成交数量
        /// </summary>
        [JsonProperty("executedQty")]
        public decimal QuantityFilled { get; set; }

        /// <summary>
        /// The currently executed amount of quote asset. Amounts to Sum(quantity * price) of executed trades for this order
        /// 未成交数量
        /// </summary>
        [JsonProperty("cummulativeQuoteQty")]
        public decimal QuoteQuantityFilled { get; set; }

        /// <summary>
        /// The status of the order
        /// 订单状态
        /// </summary>
        [JsonProperty("status"), JsonConverter(typeof(OrderStatusConverter))]
        public OrderStatus Status { get; set; }
    }
}
